import { type NextPage } from "next";
import Head from "next/head";
import Header from "~/components/Header";

const Todo: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kangaz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header title="Todo kanban - " />
        <Content />
      </main>
    </>
  );
};

export default Todo;

const Content: React.FC = () => {
  return <>Content</>;
};
